In [1]:
from pandas import Series, DataFrame
import pandas as pd
from patsy import dmatrices
import warnings
%pylab inline
warnings.filterwarnings('ignore')


Populating the interactive namespace from numpy and matplotlib


In [2]:
df = pd.read_csv(r'C:\Users\admcc\Desktop\aac_shelter_outcomes.csv')
df.columns.values

array(['age_upon_outcome', 'animal_id', 'animal_type', 'breed', 'color',
       'date_of_birth', 'datetime', 'monthyear', 'name', 'outcome_subtype',
       'outcome_type', 'sex_upon_outcome'], dtype=object)

In [3]:
df.drop_duplicates(['animal_id'], keep='last')

age_upon_outcome animal_id animal_type  \
0              2 weeks   A684346         Cat   
1               1 year   A666430         Dog   
2               1 year   A675708         Dog   
3              9 years   A680386         Dog   
4             5 months   A683115       Other   
5             4 months   A664462         Dog   
6               1 year   A693700       Other   
7              3 years   A692618         Dog   
8              1 month   A685067         Cat   
9             3 months   A678580         Cat   
10              1 year   A675405         Cat   
11             2 years   A673652         Dog   
12            2 months   A677679         Dog   
13             4 years   A640655         Dog   
14             8 years   A690350         Dog   
15             2 years   A680396         Dog   
16              1 year   A674298         Dog   
17             3 weeks   A670420         Cat   
18            2 months   A692378         Dog   
20            8 months   A673952         Cat   
21            5 months   A686497         Cat   
23            2 months   A687965         Cat   
24              1 year   A668547         Cat   
25              1 year   A689952         Dog   
26            4 months   A669621         Dog   
27            2 months   A667311         Dog   
28            4 months   A690699         Dog   
29            2 months   A682393         Cat   
30             2 weeks   A681039         Cat   
31            2 months   A682532         Cat   
...                ...       ...         ...   
78226          2 years   A764609         Dog   
78227          2 years   A756164         Dog   
78228           1 year   A765881         Cat   
78229          2 years   A763577         Dog   
78230          2 years   A764036         Dog   
78231         2 months   A758112         Cat   
78232          1 month   A758569         Cat   
78233           1 year   A765938         Cat   
78234          7 years   A765855         Dog   
78235          6 years   A765647         Dog   
78236         6 months   A765832         Cat   
78237         6 months   A765831         Cat   
78238           1 year   A765862         Dog   
78239          1 month   A764890         Dog   
78240          2 years   A765530         Dog   
78241           1 year   A765835         Dog   
78242         4 months   A765965         Dog   
78243         2 months   A765856         Dog   
78244         3 months   A754720         Dog   
78245          1 month   A764891         Dog   
78246          2 years   A738395         Dog   
78247          2 years   A761266         Dog   
78248           1 year   A725872         Dog   
78249          2 years   A761265         Dog   
78250          1 month   A764895         Dog   
78251          1 month   A764894         Dog   
78252          3 years   A764468         Dog   
78253              NaN   A766098       Other   
78254         2 months   A765858         Dog   
78255         2 months   A765857         Dog   

                                      breed                color  \
0                    Domestic Shorthair Mix         Orange Tabby   
1                                Beagle Mix          White/Brown   
2                                  Pit Bull           Blue/White   
3                   Miniature Schnauzer Mix                White   
4                                   Bat Mix                Brown   
5                            Leonberger Mix          Brown/White   
6                              Squirrel Mix                  Tan   
7                   Chihuahua Shorthair Mix                Brown   
8                    Domestic Shorthair Mix     Blue Tabby/White   
9                    Domestic Shorthair Mix          White/Black   
10                 Domestic Medium Hair Mix          Black/White   
11                   Papillon/Border Collie          Black/White   
12           Chihuahua Shorthair/Pomeranian                Black   
13     Miniature Schnauzer/Miniature Poodle                White   
14       

In [4]:
df['breed'].value_counts

<bound method Series.value_counts of 0                      Domestic Shorthair Mix
1                                  Beagle Mix
2                                    Pit Bull
3                     Miniature Schnauzer Mix
4                                     Bat Mix
5                              Leonberger Mix
6                                Squirrel Mix
7                     Chihuahua Shorthair Mix
8                      Domestic Shorthair Mix
9                      Domestic Shorthair Mix
10                   Domestic Medium Hair Mix
11                     Papillon/Border Collie
12             Chihuahua Shorthair/Pomeranian
13       Miniature Schnauzer/Miniature Poodle
14                     Labrador Retriever Mix
15                            Rat Terrier Mix
16                               Pit Bull Mix
17                     Domestic Shorthair Mix
18         German Shepherd/Labrador Retriever
19                     Domestic Shorthair Mix
20                     Domestic Shorthair M

In [5]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='%Y-%m-%d')
df['datetime'] = pd.to_datetime(df['datetime'], format='%Y-%m-%d')

df['days_alive'] = df['datetime'].sub(df['date_of_birth'], axis=0)
df['days_alive'] = df['days_alive'].dt.days
df.describe()

days_alive
count  78256.000000
mean     817.034822
std     1077.098289
min     -123.000000
25%       95.000000
50%      371.000000
75%     1096.000000
max     9137.000000

In [6]:
mask = df['name'].isnull()
df['has_name'] = 1
df['has_name'][mask] = 0

df['target'] = 0.0
mask = (df['outcome_type'] == 'Adoption')
df['target'][mask] = 1.0
df['target'].value_counts()

0.0    45144
1.0    33112
Name: target, dtype: int64

In [7]:

df['age_binned'] = pd.qcut(df['days_alive'], 5)
print df['age_binned'][:5]

0    (-123.001, 78.0]
1      (306.0, 669.0]
2      (306.0, 669.0]
3    (1222.0, 9137.0]
4       (78.0, 306.0]
Name: age_binned, dtype: category
Categories (5, interval[float64]): [(-123.001, 78.0] < (78.0, 306.0] < (306.0, 669.0] < (669.0, 1222.0] < (1222.0, 9137.0]]


In [8]:
def get_month(date):
    return date.month

In [9]:
df['month'] = df['datetime'].map(get_month)
df

age_upon_outcome animal_id animal_type  \
0              2 weeks   A684346         Cat   
1               1 year   A666430         Dog   
2               1 year   A675708         Dog   
3              9 years   A680386         Dog   
4             5 months   A683115       Other   
5             4 months   A664462         Dog   
6               1 year   A693700       Other   
7              3 years   A692618         Dog   
8              1 month   A685067         Cat   
9             3 months   A678580         Cat   
10              1 year   A675405         Cat   
11             2 years   A673652         Dog   
12            2 months   A677679         Dog   
13             4 years   A640655         Dog   
14             8 years   A690350         Dog   
15             2 years   A680396         Dog   
16              1 year   A674298         Dog   
17             3 weeks   A670420         Cat   
18            2 months   A692378         Dog   
19            2 months   A684460         Cat   
20            8 months   A673952         Cat   
21            5 months   A686497         Cat   
22             2 years   A666660         Dog   
23            2 months   A687965         Cat   
24              1 year   A668547         Cat   
25              1 year   A689952         Dog   
26            4 months   A669621         Dog   
27            2 months   A667311         Dog   
28            4 months   A690699         Dog   
29            2 months   A682393         Cat   
...                ...       ...         ...   
78226          2 years   A764609         Dog   
78227          2 years   A756164         Dog   
78228           1 year   A765881         Cat   
78229          2 years   A763577         Dog   
78230          2 years   A764036         Dog   
78231         2 months   A758112         Cat   
78232          1 month   A758569         Cat   
78233           1 year   A765938         Cat   
78234          7 years   A765855         Dog   
78235          6 years   A765647         Dog   
78236         6 months   A765832         Cat   
78237         6 months   A765831         Cat   
78238           1 year   A765862         Dog   
78239          1 month   A764890         Dog   
78240          2 years   A765530         Dog   
78241           1 year   A765835         Dog   
78242         4 months   A765965         Dog   
78243         2 months   A765856         Dog   
78244         3 months   A754720         Dog   
78245          1 month   A764891         Dog   
78246          2 years   A738395         Dog   
78247          2 years   A761266         Dog   
78248           1 year   A725872         Dog   
78249          2 years   A761265         Dog   
78250          1 month   A764895         Dog   
78251          1 month   A764894         Dog   
78252          3 years   A764468         Dog   
78253              NaN   A766098       Other   
78254         2 months   A765858         Dog   
78255         2 months   A765857         Dog   

                                      breed                color  \
0                    Domestic Shorthair Mix         Orange Tabby   
1                                Beagle Mix          White/Brown   
2                                  Pit Bull           Blue/White   
3                   Miniature Schnauzer Mix                White   
4                                   Bat Mix                Brown   
5                            Leonberger Mix          Brown/White   
6                              Squirrel Mix                  Tan   
7                   Chihuahua Shorthair Mix                Brown   
8                    Domestic Shorthair Mix     Blue Tabby/White   
9                    Domestic Shorthair Mix          White/Black   
10                 Domestic Medium Hair Mix          Black/White   
11                   Papillon/Border Collie          Black/White   
12           Chihuahua Shorthair/Pomeranian                Black   
13     Miniature Schnauzer/Miniature Poodle                White   
14       

In [10]:
categorical_columns = ['age_binned', 'animal_type', 'sex_upon_outcome', 'month']
df_dummies = pd.get_dummies(df[categorical_columns],
                            prefix=categorical_columns,
                            columns=categorical_columns)
dummy_column_names = df_dummies.columns.values
dummy_column_names[:10]

array(['age_binned_(-123.001, 78.0]', 'age_binned_(78.0, 306.0]',
       'age_binned_(306.0, 669.0]', 'age_binned_(669.0, 1222.0]',
       'age_binned_(1222.0, 9137.0]', 'animal_type_Bird',
       'animal_type_Cat', 'animal_type_Dog', 'animal_type_Livestock',
       'animal_type_Other'], dtype=object)

In [11]:
df2 = pd.concat([df, df_dummies], axis=1)

In [12]:
formula = 'target ~ 0 + {}'.format(' + '.join(['Q("{}")'.format(x) for x in dummy_column_names]))
print formula

target ~ 0 + Q("age_binned_(-123.001, 78.0]") + Q("age_binned_(78.0, 306.0]") + Q("age_binned_(306.0, 669.0]") + Q("age_binned_(669.0, 1222.0]") + Q("age_binned_(1222.0, 9137.0]") + Q("animal_type_Bird") + Q("animal_type_Cat") + Q("animal_type_Dog") + Q("animal_type_Livestock") + Q("animal_type_Other") + Q("sex_upon_outcome_Intact Female") + Q("sex_upon_outcome_Intact Male") + Q("sex_upon_outcome_Neutered Male") + Q("sex_upon_outcome_Spayed Female") + Q("sex_upon_outcome_Unknown") + Q("month_1") + Q("month_2") + Q("month_3") + Q("month_4") + Q("month_5") + Q("month_6") + Q("month_7") + Q("month_8") + Q("month_9") + Q("month_10") + Q("month_11") + Q("month_12")


In [13]:
Y, X = dmatrices(formula, df2, return_type='dataframe')

In [14]:
y = Y['target'].values
y[:10]

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.])

In [15]:
from sklearn import naive_bayes
model = naive_bayes.MultinomialNB()

In [16]:
model.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
print 'Prediction'
print model.predict(X[:10])
print 'Actual'
print y[:10]

Prediction
[ 0.  1.  1.  0.  0.  0.  0.  1.  0.  1.]
Actual
[ 0.  0.  1.  0.  0.  0.  0.  0.  1.  1.]


In [18]:
from sklearn import metrics

prediction_train = model.predict(X)
print metrics.accuracy_score(y, prediction_train)

0.733541198119


In [19]:
feature_importances = abs(model.feature_log_prob_[1] - model.feature_log_prob_[0])
feature_importances

array([ 0.0758732 ,  0.77161914,  0.00962255,  0.25524527,  0.46935594,
        0.34333434,  0.03922363,  0.12229434,  0.67093302,  2.6323164 ,
        2.08383113,  2.31533394,  0.60188336,  0.81664009,  4.207904  ,
        0.17017864,  0.10764613,  0.29755351,  0.39892568,  0.27070499,
        0.01012738,  0.27627736,  0.12816415,  0.04496438,  0.09878535,
        0.0344904 ,  0.25326377])

In [20]:
feature_importance_series = Series(feature_importances, index=X.columns.values)
feature_importance_series[:50]

Q("age_binned_(-123.001, 78.0]")       0.075873
Q("age_binned_(78.0, 306.0]")          0.771619
Q("age_binned_(306.0, 669.0]")         0.009623
Q("age_binned_(669.0, 1222.0]")        0.255245
Q("age_binned_(1222.0, 9137.0]")       0.469356
Q("animal_type_Bird")                  0.343334
Q("animal_type_Cat")                   0.039224
Q("animal_type_Dog")                   0.122294
Q("animal_type_Livestock")             0.670933
Q("animal_type_Other")                 2.632316
Q("sex_upon_outcome_Intact Female")    2.083831
Q("sex_upon_outcome_Intact Male")      2.315334
Q("sex_upon_outcome_Neutered Male")    0.601883
Q("sex_upon_outcome_Spayed Female")    0.816640
Q("sex_upon_outcome_Unknown")          4.207904
Q("month_1")                           0.170179
Q("month_2")                           0.107646
Q("month_3")                           0.297554
Q("month_4")                           0.398926
Q("month_5")                           0.270705
Q("month_6")                           0

In [21]:
feature_importance_series.sort_values(ascending=False)[:50]

Q("sex_upon_outcome_Unknown")          4.207904
Q("animal_type_Other")                 2.632316
Q("sex_upon_outcome_Intact Male")      2.315334
Q("sex_upon_outcome_Intact Female")    2.083831
Q("sex_upon_outcome_Spayed Female")    0.816640
Q("age_binned_(78.0, 306.0]")          0.771619
Q("animal_type_Livestock")             0.670933
Q("sex_upon_outcome_Neutered Male")    0.601883
Q("age_binned_(1222.0, 9137.0]")       0.469356
Q("month_4")                           0.398926
Q("animal_type_Bird")                  0.343334
Q("month_3")                           0.297554
Q("month_7")                           0.276277
Q("month_5")                           0.270705
Q("age_binned_(669.0, 1222.0]")        0.255245
Q("month_12")                          0.253264
Q("month_1")                           0.170179
Q("month_8")                           0.128164
Q("animal_type_Dog")                   0.122294
Q("month_2")                           0.107646
Q("month_10")                          0

In [22]:
top_10_feature_indices = feature_importance_series.sort_values(ascending=False)[:50].index.values

In [23]:
inter_class_differences = model.feature_log_prob_[1] - model.feature_log_prob_[0]
new_feature_importance_series = Series(inter_class_differences, index=X.columns.values)

new_feature_importance_series[top_10_feature_indices]

Q("sex_upon_outcome_Unknown")         -4.207904
Q("animal_type_Other")                -2.632316
Q("sex_upon_outcome_Intact Male")     -2.315334
Q("sex_upon_outcome_Intact Female")   -2.083831
Q("sex_upon_outcome_Spayed Female")    0.816640
Q("age_binned_(78.0, 306.0]")          0.771619
Q("animal_type_Livestock")            -0.670933
Q("sex_upon_outcome_Neutered Male")    0.601883
Q("age_binned_(1222.0, 9137.0]")      -0.469356
Q("month_4")                          -0.398926
Q("animal_type_Bird")                 -0.343334
Q("month_3")                          -0.297554
Q("month_7")                           0.276277
Q("month_5")                          -0.270705
Q("age_binned_(669.0, 1222.0]")       -0.255245
Q("month_12")                          0.253264
Q("month_1")                           0.170179
Q("month_8")                           0.128164
Q("animal_type_Dog")                   0.122294
Q("month_2")                           0.107646
Q("month_10")                         -0

In [24]:
import sys
sys.setrecursionlimit(10000)

In [25]:
df_copy = df.copy()
mask = df_copy['animal_type'].isin(["Dog", "Cat"])
df_copy = df_copy[mask]
df_copy
df_copy['target'] = 0.0
mask = (df['outcome_type'] == 'Adoption')
df_copy['target'][mask] = 1.0
df_copy['target'].value_counts()

0.0    40880
1.0    32784
Name: target, dtype: int64

In [26]:
categorical_columns = ['age_binned', 'sex_upon_outcome', 'month']
df_dummies = pd.get_dummies(df[categorical_columns],
                            prefix=categorical_columns,
                            columns=categorical_columns)
dummy_column_names = df_dummies.columns.values
dummy_column_names[:10]

array(['age_binned_(-123.001, 78.0]', 'age_binned_(78.0, 306.0]',
       'age_binned_(306.0, 669.0]', 'age_binned_(669.0, 1222.0]',
       'age_binned_(1222.0, 9137.0]', 'sex_upon_outcome_Intact Female',
       'sex_upon_outcome_Intact Male', 'sex_upon_outcome_Neutered Male',
       'sex_upon_outcome_Spayed Female', 'sex_upon_outcome_Unknown'], dtype=object)

In [27]:
df3 = pd.concat([df_copy, df_dummies], axis=1)

In [28]:
formula = 'target ~ 0 + {}'.format(' + '.join(['Q("{}")'.format(x) for x in dummy_column_names]))
print formula

target ~ 0 + Q("age_binned_(-123.001, 78.0]") + Q("age_binned_(78.0, 306.0]") + Q("age_binned_(306.0, 669.0]") + Q("age_binned_(669.0, 1222.0]") + Q("age_binned_(1222.0, 9137.0]") + Q("sex_upon_outcome_Intact Female") + Q("sex_upon_outcome_Intact Male") + Q("sex_upon_outcome_Neutered Male") + Q("sex_upon_outcome_Spayed Female") + Q("sex_upon_outcome_Unknown") + Q("month_1") + Q("month_2") + Q("month_3") + Q("month_4") + Q("month_5") + Q("month_6") + Q("month_7") + Q("month_8") + Q("month_9") + Q("month_10") + Q("month_11") + Q("month_12")


In [29]:
Y, X = dmatrices(formula, df3, return_type='dataframe')

In [30]:
y = Y['target'].values
y[:10]

array([ 0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.])

In [31]:
model.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [32]:
print 'Prediction'
print model.predict(X[:10])
print 'Actual'
print y[:10]

Prediction
[ 0.  1.  1.  0.  0.  1.  0.  1.  1.  0.]
Actual
[ 0.  0.  1.  0.  0.  0.  1.  1.  0.  0.]


In [33]:
feature_importances = abs(model.feature_log_prob_[1] - model.feature_log_prob_[0])
feature_importances

array([ 0.10989251,  0.78658468,  0.12416694,  0.24789665,  0.55182773,
        2.20125766,  2.48752658,  0.50903803,  0.72406273,  7.01064725,
        0.14729117,  0.12442904,  0.17395665,  0.37837566,  0.29496977,
        0.02218546,  0.26084194,  0.13414308,  0.07010159,  0.10110577,
        0.00864699,  0.23260878])

In [34]:
feature_importance_series = Series(feature_importances, index=X.columns.values)
feature_importance_series[:50]

Q("age_binned_(-123.001, 78.0]")       0.109893
Q("age_binned_(78.0, 306.0]")          0.786585
Q("age_binned_(306.0, 669.0]")         0.124167
Q("age_binned_(669.0, 1222.0]")        0.247897
Q("age_binned_(1222.0, 9137.0]")       0.551828
Q("sex_upon_outcome_Intact Female")    2.201258
Q("sex_upon_outcome_Intact Male")      2.487527
Q("sex_upon_outcome_Neutered Male")    0.509038
Q("sex_upon_outcome_Spayed Female")    0.724063
Q("sex_upon_outcome_Unknown")          7.010647
Q("month_1")                           0.147291
Q("month_2")                           0.124429
Q("month_3")                           0.173957
Q("month_4")                           0.378376
Q("month_5")                           0.294970
Q("month_6")                           0.022185
Q("month_7")                           0.260842
Q("month_8")                           0.134143
Q("month_9")                           0.070102
Q("month_10")                          0.101106
Q("month_11")                          0

In [35]:
feature_importance_series.sort_values(ascending=False)[:50]

Q("sex_upon_outcome_Unknown")          7.010647
Q("sex_upon_outcome_Intact Male")      2.487527
Q("sex_upon_outcome_Intact Female")    2.201258
Q("age_binned_(78.0, 306.0]")          0.786585
Q("sex_upon_outcome_Spayed Female")    0.724063
Q("age_binned_(1222.0, 9137.0]")       0.551828
Q("sex_upon_outcome_Neutered Male")    0.509038
Q("month_4")                           0.378376
Q("month_5")                           0.294970
Q("month_7")                           0.260842
Q("age_binned_(669.0, 1222.0]")        0.247897
Q("month_12")                          0.232609
Q("month_3")                           0.173957
Q("month_1")                           0.147291
Q("month_8")                           0.134143
Q("month_2")                           0.124429
Q("age_binned_(306.0, 669.0]")         0.124167
Q("age_binned_(-123.001, 78.0]")       0.109893
Q("month_10")                          0.101106
Q("month_9")                           0.070102
Q("month_6")                           0

In [36]:
top_10_feature_indices = feature_importance_series.sort_values(ascending=False)[:50].index.values

In [37]:
inter_class_differences = model.feature_log_prob_[1] - model.feature_log_prob_[0]
new_feature_importance_series = Series(inter_class_differences, index=X.columns.values)

new_feature_importance_series[top_10_feature_indices]

Q("sex_upon_outcome_Unknown")         -7.010647
Q("sex_upon_outcome_Intact Male")     -2.487527
Q("sex_upon_outcome_Intact Female")   -2.201258
Q("age_binned_(78.0, 306.0]")          0.786585
Q("sex_upon_outcome_Spayed Female")    0.724063
Q("age_binned_(1222.0, 9137.0]")      -0.551828
Q("sex_upon_outcome_Neutered Male")    0.509038
Q("month_4")                          -0.378376
Q("month_5")                          -0.294970
Q("month_7")                           0.260842
Q("age_binned_(669.0, 1222.0]")       -0.247897
Q("month_12")                          0.232609
Q("month_3")                          -0.173957
Q("month_1")                           0.147291
Q("month_8")                           0.134143
Q("month_2")                           0.124429
Q("age_binned_(306.0, 669.0]")         0.124167
Q("age_binned_(-123.001, 78.0]")      -0.109893
Q("month_10")                         -0.101106
Q("month_9")                          -0.070102
Q("month_6")                          -0

In [38]:
df[df['animal_type'] == "Other"]["breed"].value_counts().head()

Bat Mix          1286
Bat               799
Raccoon Mix       465
Rabbit Sh Mix     291
Raccoon           230
Name: breed, dtype: int64

In [39]:
df[df['animal_type'] == "Dog"]["breed"].value_counts()[:100]

Pit Bull Mix                                6135
Chihuahua Shorthair Mix                     4733
Labrador Retriever Mix                      4608
German Shepherd Mix                         1892
Australian Cattle Dog Mix                   1059
Dachshund Mix                                798
Boxer Mix                                    674
Miniature Poodle Mix                         648
Border Collie Mix                            646
Catahoula Mix                                476
Rat Terrier Mix                              456
Australian Shepherd Mix                      454
Yorkshire Terrier Mix                        437
Siberian Husky Mix                           418
Jack Russell Terrier Mix                     416
Miniature Schnauzer Mix                      392
Beagle Mix                                   384
Chihuahua Longhair Mix                       359
Staffordshire Mix                            350
Great Pyrenees Mix                           330
Cairn Terrier Mix   

In [40]:
df['breed_count'] = df.groupby(['breed'])['animal_type'].transform('count')
df_breed = df[df['animal_type'] == "Dog"]
df_breed = df_breed[df_breed['breed_count'] >= 500]
df_breed

age_upon_outcome animal_id animal_type                      breed  \
7              3 years   A692618         Dog    Chihuahua Shorthair Mix   
14             8 years   A690350         Dog     Labrador Retriever Mix   
16              1 year   A674298         Dog               Pit Bull Mix   
27            2 months   A667311         Dog     Labrador Retriever Mix   
28            4 months   A690699         Dog    Chihuahua Shorthair Mix   
32            3 months   A669918         Dog     Labrador Retriever Mix   
34            12 years   A678098         Dog     Labrador Retriever Mix   
36             2 years   A677038         Dog    Chihuahua Shorthair Mix   
37             4 years   A665344         Dog    Chihuahua Shorthair Mix   
45             3 years   A647382         Dog          Border Collie Mix   
47             2 years   A660098         Dog               Pit Bull Mix   
48              1 year   A693005         Dog                  Boxer Mix   
53             6 years   A545127         Dog               Pit Bull Mix   
54             3 years   A661023         Dog       Miniature Poodle Mix   
55             3 years   A673648         Dog               Pit Bull Mix   
56              5 days   A674466         Dog               Pit Bull Mix   
58              1 year   A677479         Dog    Chihuahua Shorthair Mix   
62            10 years   A688079         Dog     Labrador Retriever Mix   
64              1 year   A666831         Dog    Chihuahua Shorthair Mix   
65            5 months   A683939         Dog               Pit Bull Mix   
72             3 years   A674267         Dog    Chihuahua Shorthair Mix   
76              2 days   A680147         Dog     Labrador Retriever Mix   
79            2 months   A667384         Dog               Pit Bull Mix   
84             1 month   A671481         Dog    Chihuahua Shorthair Mix   
95            14 years   A562649         Dog          Border Collie Mix   
97              1 year   A688904         Dog        German Shepherd Mix   
100             1 year   A668644         Dog    Chihuahua Shorthair Mix   
104           2 months   A675362         Dog     Labrador Retriever Mix   
108            5 years   A670525         Dog              Dachshund Mix   
109            4 years   A646578         Dog     Labrador Retriever Mix   
...                ...       ...         ...                        ...   
78136          4 years   A759504         Dog     Labrador Retriever Mix   
78138          4 years   A765360         Dog               Pit Bull Mix   
78140         9 months   A765672         Dog               Pit Bull Mix   
78142          2 years   A765952         Dog              Dachshund Mix   
78143         9 months   A731032         Dog               Pit Bull Mix   
78144           1 year   A731032         Dog               Pit Bull Mix   
78145         8 months   A731032         Dog               Pit Bull Mix   
78146        10 months   A731032         Dog               Pit Bull Mix   
78148         6 months   A765421         Dog  Australian Cattle Dog Mix   
78154          7 years   A765895         Dog               Pit Bull Mix   
78160         2 months   A764650         Dog                  Boxer Mix   
78172          3 years   A765738         Dog    Chihuahua Shorthair Mix   
78177         12 years   A720304         Dog               Pit Bull Mix   
78178          2 years   A765753         Dog               Pit Bull Mix   
78179          3 years   A765476         Dog               Pit Bull Mix   
78181          2 years   A765806         Dog    Chihuahua Shorthair Mix   
78182          2 years   A765368         Dog        German Shepherd Mix   
78188           1 year   A766024         Dog  Australian Cattle Dog Mix   
78198          8 years   A623561         Dog               Pit Bull Mix   
78205         10 years   A766035         Dog    Chihuahua Shorthair Mix   
78215           1 year   A763760         Dog          Border Collie Mix   
78229          2 years   A76357

In [41]:
df_breed['color_count'] = df_breed.groupby(['color'])['animal_type'].transform('count')
df_breed_color = df_breed[df_breed['color_count'] >= 1000]
df_breed_color

age_upon_outcome animal_id animal_type                      breed  \
7              3 years   A692618         Dog    Chihuahua Shorthair Mix   
14             8 years   A690350         Dog     Labrador Retriever Mix   
32            3 months   A669918         Dog     Labrador Retriever Mix   
34            12 years   A678098         Dog     Labrador Retriever Mix   
45             3 years   A647382         Dog          Border Collie Mix   
48              1 year   A693005         Dog                  Boxer Mix   
53             6 years   A545127         Dog               Pit Bull Mix   
58              1 year   A677479         Dog    Chihuahua Shorthair Mix   
72             3 years   A674267         Dog    Chihuahua Shorthair Mix   
97              1 year   A688904         Dog        German Shepherd Mix   
115            9 years   A687494         Dog    Chihuahua Shorthair Mix   
118           8 months   A684123         Dog          Border Collie Mix   
131             1 year   A672839         Dog              Dachshund Mix   
138             1 year   A675177         Dog     Labrador Retriever Mix   
148           2 months   A664490         Dog     Labrador Retriever Mix   
163           5 months   A688062         Dog     Labrador Retriever Mix   
165            3 years   A687004         Dog               Pit Bull Mix   
166             1 year   A669193         Dog               Pit Bull Mix   
168           2 months   A668531         Dog  Australian Cattle Dog Mix   
171           2 months   A663020         Dog    Chihuahua Shorthair Mix   
179           6 months   A667941         Dog     Labrador Retriever Mix   
184            3 years   A625324         Dog               Pit Bull Mix   
206            6 years   A672684         Dog               Pit Bull Mix   
211            1 month   A682822         Dog    Chihuahua Shorthair Mix   
223             1 year   A682584         Dog    Chihuahua Shorthair Mix   
248           13 years   A352555         Dog     Labrador Retriever Mix   
249            8 years   A669124         Dog       Miniature Poodle Mix   
264             1 year   A685756         Dog        German Shepherd Mix   
265            3 years   A689995         Dog               Pit Bull Mix   
283            4 years   A664943         Dog     Labrador Retriever Mix   
...                ...       ...         ...                        ...   
77907          3 years   A765695         Dog               Pit Bull Mix   
77912           1 year   A765369         Dog    Chihuahua Shorthair Mix   
77919           1 year   A749196         Dog     Labrador Retriever Mix   
77927          2 years   A765028         Dog    Chihuahua Shorthair Mix   
77932         2 months   A764536         Dog    Chihuahua Shorthair Mix   
77933         4 months   A765483         Dog     Labrador Retriever Mix   
77936          7 years   A765575         Dog    Chihuahua Shorthair Mix   
77966         11 years   A492949         Dog     Labrador Retriever Mix   
77972          2 years   A765782         Dog     Labrador Retriever Mix   
77974           1 year   A765410         Dog               Pit Bull Mix   
78013          2 years   A762550         Dog    Chihuahua Shorthair Mix   
78015          3 years   A765818         Dog               Pit Bull Mix   
78016          2 years   A762550         Dog    Chihuahua Shorthair Mix   
78019         7 months   A761022         Dog               Pit Bull Mix   
78021           1 year   A765279         Dog        German Shepherd Mix   
78022           1 year   A765735         Dog    Chihuahua Shorthair Mix   
78059          3 years   A765093         Dog     Labrador Retriever Mix   
78078          2 years   A765719         Dog    Chihuahua Shorthair Mix   
78081              NaN   A765899         Dog       Miniature Poodle Mix   
78086         2 months   A765715         Dog     Labrador Retriever Mix   
78104        10 months   A765513         Dog               Pit Bull Mix   
78105           1 year   A74436

In [42]:
df_breed_color['target'] = 0.0
mask = (df_breed_color['outcome_type'] == 'Adoption')
df_breed_color['target'][mask] = 1.0
df_breed_color['target'].value_counts()

0.0    4940
1.0    4067
Name: target, dtype: int64

In [43]:
categorical_columns = ['age_binned', 'sex_upon_outcome', 'month', 'breed']
df_dummies = pd.get_dummies(df[categorical_columns],
                            prefix=categorical_columns,
                            columns=categorical_columns)
dummy_column_names = df_dummies.columns.values
dummy_column_names[:10]

array(['age_binned_(-123.001, 78.0]', 'age_binned_(78.0, 306.0]',
       'age_binned_(306.0, 669.0]', 'age_binned_(669.0, 1222.0]',
       'age_binned_(1222.0, 9137.0]', 'sex_upon_outcome_Intact Female',
       'sex_upon_outcome_Intact Male', 'sex_upon_outcome_Neutered Male',
       'sex_upon_outcome_Spayed Female', 'sex_upon_outcome_Unknown'], dtype=object)

In [44]:
df4 = pd.concat([df_breed_color, df_dummies], axis=1)

In [45]:
formula = 'target ~ 0 + {}'.format(' + '.join(['Q("{}")'.format(x) for x in dummy_column_names]))
print formula

target ~ 0 + Q("age_binned_(-123.001, 78.0]") + Q("age_binned_(78.0, 306.0]") + Q("age_binned_(306.0, 669.0]") + Q("age_binned_(669.0, 1222.0]") + Q("age_binned_(1222.0, 9137.0]") + Q("sex_upon_outcome_Intact Female") + Q("sex_upon_outcome_Intact Male") + Q("sex_upon_outcome_Neutered Male") + Q("sex_upon_outcome_Spayed Female") + Q("sex_upon_outcome_Unknown") + Q("month_1") + Q("month_2") + Q("month_3") + Q("month_4") + Q("month_5") + Q("month_6") + Q("month_7") + Q("month_8") + Q("month_9") + Q("month_10") + Q("month_11") + Q("month_12") + Q("breed_Abyssinian Mix") + Q("breed_Affenpinscher Mix") + Q("breed_Afghan Hound Mix") + Q("breed_Afghan Hound/Labrador Retriever") + Q("breed_African Mix") + Q("breed_Airedale Terrier") + Q("breed_Airedale Terrier Mix") + Q("breed_Airedale Terrier/Irish Terrier") + Q("breed_Airedale Terrier/Labrador Retriever") + Q("breed_Airedale Terrier/Miniature Schnauzer") + Q("breed_Akbash Mix") + Q("breed_Akita") + Q("breed_Akita Mix") + Q("breed_Akita/Austra

In [46]:
Y, X = dmatrices(formula, df4, return_type='dataframe')

In [47]:
y = Y['target'].values
y[:10]

array([ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.])

In [48]:
model.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [49]:
print 'Prediction'
print model.predict(X[:10])
print 'Actual'
print y[:10]

Prediction
[ 1.  0.  1.  0.  1.  1.  0.  1.  0.  1.]
Actual
[ 0.  0.  1.  1.  1.  0.  0.  1.  1.  0.]


In [50]:
prediction_train = model.predict(X)
print metrics.accuracy_score(y, prediction_train)

0.720883757078


In [51]:
feature_importances = abs(model.feature_log_prob_[1] - model.feature_log_prob_[0])
feature_importances

array([ 0.30734893,  0.54179   ,  0.33108624, ...,  0.17356906,
        0.17356906,  0.17356906])

In [52]:
feature_importance_series = Series(feature_importances, index=X.columns.values)
feature_importance_series[:20]

Q("age_binned_(-123.001, 78.0]")                                  0.307349
Q("age_binned_(78.0, 306.0]")                                     0.541790
Q("age_binned_(306.0, 669.0]")                                    0.331086
Q("age_binned_(669.0, 1222.0]")                                   0.250560
Q("age_binned_(1222.0, 9137.0]")                                  0.715927
Q("sex_upon_outcome_Intact Female")                               2.448056
Q("sex_upon_outcome_Intact Male")                                 2.624820
Q("sex_upon_outcome_Neutered Male")                               0.301855
Q("sex_upon_outcome_Spayed Female")                               0.543411
Q("sex_upon_outcome_Unknown")                                     4.170236
Q("month_1")                                                      0.043694
Q("month_2")                                                      0.246772
Q("month_3")                                                      0.182727
Q("month_4")             

In [53]:
feature_importance_series.sort_values(ascending=False)[:20]

Q("sex_upon_outcome_Unknown")                         4.170236
Q("sex_upon_outcome_Intact Male")                     2.624820
Q("sex_upon_outcome_Intact Female")                   2.448056
Q("age_binned_(1222.0, 9137.0]")                      0.715927
Q("breed_Australian Cattle Dog Mix")                  0.612482
Q("sex_upon_outcome_Spayed Female")                   0.543411
Q("age_binned_(78.0, 306.0]")                         0.541790
Q("breed_Pit Bull Mix")                               0.427551
Q("age_binned_(306.0, 669.0]")                        0.331086
Q("breed_Miniature Poodle Mix")                       0.327911
Q("age_binned_(-123.001, 78.0]")                      0.307349
Q("sex_upon_outcome_Neutered Male")                   0.301855
Q("month_8")                                          0.277110
Q("month_5")                                          0.253206
Q("age_binned_(669.0, 1222.0]")                       0.250560
Q("month_2")                                          0

In [54]:
top_10_feature_indices = feature_importance_series.sort_values(ascending=False)[:20].index.values

In [55]:
inter_class_differences = model.feature_log_prob_[1] - model.feature_log_prob_[0]
new_feature_importance_series = Series(inter_class_differences, index=X.columns.values)

new_feature_importance_series[top_10_feature_indices]

Q("sex_upon_outcome_Unknown")                        -4.170236
Q("sex_upon_outcome_Intact Male")                    -2.624820
Q("sex_upon_outcome_Intact Female")                  -2.448056
Q("age_binned_(1222.0, 9137.0]")                     -0.715927
Q("breed_Australian Cattle Dog Mix")                  0.612482
Q("sex_upon_outcome_Spayed Female")                   0.543411
Q("age_binned_(78.0, 306.0]")                         0.541790
Q("breed_Pit Bull Mix")                              -0.427551
Q("age_binned_(306.0, 669.0]")                        0.331086
Q("breed_Miniature Poodle Mix")                      -0.327911
Q("age_binned_(-123.001, 78.0]")                      0.307349
Q("sex_upon_outcome_Neutered Male")                   0.301855
Q("month_8")                                          0.277110
Q("month_5")                                         -0.253206
Q("age_binned_(669.0, 1222.0]")                      -0.250560
Q("month_2")                                          0