In [1]:
from pandas import Series, DataFrame
import pandas as pd
from patsy import dmatrices
import warnings
%pylab inline
warnings.filterwarnings('ignore')


Populating the interactive namespace from numpy and matplotlib


In [2]:
df = pd.read_csv(r'C:\Users\admcc\Desktop\aac_shelter_outcomes.csv')
df.columns.values

array(['age_upon_outcome', 'animal_id', 'animal_type', 'breed', 'color',
       'date_of_birth', 'datetime', 'monthyear', 'name', 'outcome_subtype',
       'outcome_type', 'sex_upon_outcome'], dtype=object)

In [3]:
df

age_upon_outcome animal_id animal_type  \
0              2 weeks   A684346         Cat   
1               1 year   A666430         Dog   
2               1 year   A675708         Dog   
3              9 years   A680386         Dog   
4             5 months   A683115       Other   
5             4 months   A664462         Dog   
6               1 year   A693700       Other   
7              3 years   A692618         Dog   
8              1 month   A685067         Cat   
9             3 months   A678580         Cat   
10              1 year   A675405         Cat   
11             2 years   A673652         Dog   
12            2 months   A677679         Dog   
13             4 years   A640655         Dog   
14             8 years   A690350         Dog   
15             2 years   A680396         Dog   
16              1 year   A674298         Dog   
17             3 weeks   A670420         Cat   
18            2 months   A692378         Dog   
19            2 months   A684460         Cat   
20            8 months   A673952         Cat   
21            5 months   A686497         Cat   
22             2 years   A666660         Dog   
23            2 months   A687965         Cat   
24              1 year   A668547         Cat   
25              1 year   A689952         Dog   
26            4 months   A669621         Dog   
27            2 months   A667311         Dog   
28            4 months   A690699         Dog   
29            2 months   A682393         Cat   
...                ...       ...         ...   
78226          2 years   A764609         Dog   
78227          2 years   A756164         Dog   
78228           1 year   A765881         Cat   
78229          2 years   A763577         Dog   
78230          2 years   A764036         Dog   
78231         2 months   A758112         Cat   
78232          1 month   A758569         Cat   
78233           1 year   A765938         Cat   
78234          7 years   A765855         Dog   
78235          6 years   A765647         Dog   
78236         6 months   A765832         Cat   
78237         6 months   A765831         Cat   
78238           1 year   A765862         Dog   
78239          1 month   A764890         Dog   
78240          2 years   A765530         Dog   
78241           1 year   A765835         Dog   
78242         4 months   A765965         Dog   
78243         2 months   A765856         Dog   
78244         3 months   A754720         Dog   
78245          1 month   A764891         Dog   
78246          2 years   A738395         Dog   
78247          2 years   A761266         Dog   
78248           1 year   A725872         Dog   
78249          2 years   A761265         Dog   
78250          1 month   A764895         Dog   
78251          1 month   A764894         Dog   
78252          3 years   A764468         Dog   
78253              NaN   A766098       Other   
78254         2 months   A765858         Dog   
78255         2 months   A765857         Dog   

                                      breed                color  \
0                    Domestic Shorthair Mix         Orange Tabby   
1                                Beagle Mix          White/Brown   
2                                  Pit Bull           Blue/White   
3                   Miniature Schnauzer Mix                White   
4                                   Bat Mix                Brown   
5                            Leonberger Mix          Brown/White   
6                              Squirrel Mix                  Tan   
7                   Chihuahua Shorthair Mix                Brown   
8                    Domestic Shorthair Mix     Blue Tabby/White   
9                    Domestic Shorthair Mix          White/Black   
10                 Domestic Medium Hair Mix          Black/White   
11                   Papillon/Border Collie          Black/White   
12           Chihuahua Shorthair/Pomeranian                Black   
13     Miniature Schnauzer/Miniature Poodle                White   
14       

In [5]:
df['breed'].value_counts

<bound method Series.value_counts of 0                      Domestic Shorthair Mix
1                                  Beagle Mix
2                                    Pit Bull
3                     Miniature Schnauzer Mix
4                                     Bat Mix
5                              Leonberger Mix
6                                Squirrel Mix
7                     Chihuahua Shorthair Mix
8                      Domestic Shorthair Mix
9                      Domestic Shorthair Mix
10                   Domestic Medium Hair Mix
11                     Papillon/Border Collie
12             Chihuahua Shorthair/Pomeranian
13       Miniature Schnauzer/Miniature Poodle
14                     Labrador Retriever Mix
15                            Rat Terrier Mix
16                               Pit Bull Mix
17                     Domestic Shorthair Mix
18         German Shepherd/Labrador Retriever
19                     Domestic Shorthair Mix
20                     Domestic Shorthair M

In [37]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='%Y-%m-%d')
df['datetime'] = pd.to_datetime(df['datetime'], format='%Y-%m-%d')

df['days_alive'] = df['datetime'].sub(df['date_of_birth'], axis=0)
df['days_alive'] = df['days_alive'].dt.days
df.describe()

days_alive        target
count  78256.000000  78256.000000
mean     817.039946      0.423086
std     1077.094186      0.494052
min        0.000000      0.000000
25%       95.000000      0.000000
50%      371.000000      0.000000
75%     1096.000000      1.000000
max     9137.000000      1.000000

In [38]:
df['target'] = 0.0
mask = (df['outcome_type'] == 'Adoption')
df['target'][mask] = 1.0
df['target'].value_counts()

0.0    45147
1.0    33109
Name: target, dtype: int64

In [39]:

df['age_binned'] = pd.qcut(df['days_alive'], 5)
print df['age_binned'][:5]

0      (-0.001, 78.0]
1      (306.0, 669.0]
2      (306.0, 669.0]
3    (1222.0, 9137.0]
4       (78.0, 306.0]
Name: age_binned, dtype: category
Categories (5, interval[float64]): [(-0.001, 78.0] < (78.0, 306.0] < (306.0, 669.0] < (669.0, 1222.0] < (1222.0, 9137.0]]


In [40]:
categorical_columns = ['age_binned', 'animal_type', 'sex_upon_outcome']
df_dummies = pd.get_dummies(df[categorical_columns],
                            prefix=categorical_columns,
                            columns=categorical_columns)
dummy_column_names = df_dummies.columns.values
dummy_column_names[:10]

array(['age_binned_(-0.001, 78.0]', 'age_binned_(78.0, 306.0]',
       'age_binned_(306.0, 669.0]', 'age_binned_(669.0, 1222.0]',
       'age_binned_(1222.0, 9137.0]', 'animal_type_0', 'animal_type_Bird',
       'animal_type_Cat', 'animal_type_Dog', 'animal_type_Livestock'], dtype=object)

In [41]:
df2 = pd.concat([df, df_dummies], axis=1)

In [42]:
formula = 'target ~ 0 + {}'.format(' + '.join(['Q("{}")'.format(x) for x in dummy_column_names]))
print formula

target ~ 0 + Q("age_binned_(-0.001, 78.0]") + Q("age_binned_(78.0, 306.0]") + Q("age_binned_(306.0, 669.0]") + Q("age_binned_(669.0, 1222.0]") + Q("age_binned_(1222.0, 9137.0]") + Q("animal_type_0") + Q("animal_type_Bird") + Q("animal_type_Cat") + Q("animal_type_Dog") + Q("animal_type_Livestock") + Q("animal_type_Other") + Q("sex_upon_outcome_0") + Q("sex_upon_outcome_Intact Female") + Q("sex_upon_outcome_Intact Male") + Q("sex_upon_outcome_Neutered Male") + Q("sex_upon_outcome_Spayed Female") + Q("sex_upon_outcome_Unknown")


In [43]:
Y, X = dmatrices(formula, df2, return_type='dataframe')

In [44]:
y = Y['target'].values
y[:10]

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.])

In [45]:
from sklearn import naive_bayes
model = naive_bayes.MultinomialNB()

In [46]:
model.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [36]:
print 'Prediction'
print model.predict(X[:10])
print 'Actual'
print y[:10]

Prediction
[ 0.  1.  1.  0.  0.  0.  0.  1.  0.  1.]
Actual
[ 0.  0.  1.  0.  0.  0.  0.  0.  1.  1.]


In [47]:
from sklearn import metrics

prediction_train = model.predict(X)
print metrics.accuracy_score(y, prediction_train)

0.736211919853


In [48]:
feature_importances = abs(model.feature_log_prob_[1] - model.feature_log_prob_[0])
feature_importances

array([ 0.07650386,  0.7717812 ,  0.00946049,  0.25508321,  0.46919388,
        1.88716629,  0.34317228,  0.03940836,  0.1224892 ,  0.67077096,
        2.63215434,  1.88716629,  2.08485778,  2.31505959,  0.60206674,
        0.8168441 ,  4.20758822])

In [49]:
feature_importance_series = Series(feature_importances, index=X.columns.values)
feature_importance_series[:10]

Q("age_binned_(-0.001, 78.0]")      0.076504
Q("age_binned_(78.0, 306.0]")       0.771781
Q("age_binned_(306.0, 669.0]")      0.009460
Q("age_binned_(669.0, 1222.0]")     0.255083
Q("age_binned_(1222.0, 9137.0]")    0.469194
Q("animal_type_0")                  1.887166
Q("animal_type_Bird")               0.343172
Q("animal_type_Cat")                0.039408
Q("animal_type_Dog")                0.122489
Q("animal_type_Livestock")          0.670771
dtype: float64

In [50]:
feature_importance_series.sort_values(ascending=False)[:10]

Q("sex_upon_outcome_Unknown")          4.207588
Q("animal_type_Other")                 2.632154
Q("sex_upon_outcome_Intact Male")      2.315060
Q("sex_upon_outcome_Intact Female")    2.084858
Q("sex_upon_outcome_0")                1.887166
Q("animal_type_0")                     1.887166
Q("sex_upon_outcome_Spayed Female")    0.816844
Q("age_binned_(78.0, 306.0]")          0.771781
Q("animal_type_Livestock")             0.670771
Q("sex_upon_outcome_Neutered Male")    0.602067
dtype: float64

In [51]:
top_10_feature_indices = feature_importance_series.sort_values(ascending=False)[:10].index.values

In [52]:
inter_class_differences = model.feature_log_prob_[1] - model.feature_log_prob_[0]
new_feature_importance_series = Series(inter_class_differences, index=X.columns.values)

new_feature_importance_series[top_10_feature_indices]

Q("sex_upon_outcome_Unknown")         -4.207588
Q("animal_type_Other")                -2.632154
Q("sex_upon_outcome_Intact Male")     -2.315060
Q("sex_upon_outcome_Intact Female")   -2.084858
Q("sex_upon_outcome_0")               -1.887166
Q("animal_type_0")                    -1.887166
Q("sex_upon_outcome_Spayed Female")    0.816844
Q("age_binned_(78.0, 306.0]")          0.771781
Q("animal_type_Livestock")            -0.670771
Q("sex_upon_outcome_Neutered Male")    0.602067
dtype: float64